spring:
  main:
    banner-mode: off
    lazy-initialization: true
  application.name: template-spring-kotlin-app
  output.ansi.enabled: detect

logging:
  pattern:
    level: "%clr(%-5p)"
    console: "%date{yyyy.MM.dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} %clr([%thread]){magenta} %clr(%logger{-1}){cyan}->%clr(%method){blue}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  register-shutdown-hook: true
  level.root: INFO
